[tool.poetry]
name = "D47crunch"
version = "2.0.0-beta"
description = "Standardization and analytical error propagation of Δ47 and Δ48 clumped-isotope measurements"
authors = ["Mathieu Daëron <mathieu@daeron.fr>"]
license = "3-Clause BSD"

[tool.poetry.dependencies]
python = ">= 3.8, < 3.10"
numpy = "^1.21.1"
scipy = "^1.7.0"
lmfit = "^1.0.2"
matplotlib = "^3.4.2"

[tool.poetry.dev-dependencies]
pdoc3 = "^0.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
